# Generated by Django 4.2.9 on 2024-06-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cadastro_de_cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(blank=True, max_length=100, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=100, null=True)),
                ('logadouro', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('número', models.IntegerField(blank=True, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'), ('DF', 'Distrito Federal')], max_length=100, null=True)),
                ('pessoa_de_contato', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(blank=True, max_length=100, null=True)),
                ('email_contato', models.CharField(blank=True, max_length=100, null=True)),
                ('ramo', models.CharField(blank=True, choices=[('ALIMENTAÇÃO', 'Alimentação'), ('INDUSTRIA', 'Indústria'), ('COMERCIO', 'Comércio'), ('SAUDE', 'Saúde'), ('SERVICOS', 'Serviços')], max_length=100, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('bancos_utilizados', models.CharField(blank=True, max_length=100, null=True)),
                ('servicos_contratados', models.CharField(blank=True, max_length=100, null=True)),
                ('responsavel_conciliacao', models.CharField(blank=True, max_length=100, null=True)),
                ('responsavel_apresentacao', models.CharField(blank=True, max_length=100, null=True)),
                ('funcionarios', models.TextField(blank=True, max_length=500, null=True)),
                ('contas_fixas', models.TextField(blank=True, max_length=500, null=True)),
                ('classificacoes', models.TextField(blank=True, max_length=500, null=True)),
                ('principais_fornecedores', models.TextField(blank=True, max_length=500, null=True)),
                ('observacoes', models.TextField(blank=True, max_length=500, null=True)),
                ('sugestoes', models.TextField(blank=True, max_length=500, null=True)),
                ('historico', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
