# Generated by Django 5.0.6 on 2025-06-24 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('hpinicial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro_de_cliente',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hpinicial.tenant'),
        ),
        migrations.AddField(
            model_name='cadastro_de_cliente',
            name='ramo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.ramo'),
        ),
    ]
