# Generated by Django 5.0.6 on 2024-08-01 14:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_ramo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro_de_cliente',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
