# Generated by Django 5.0.6 on 2024-08-01 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_cadastro_de_cliente_criado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_de_cliente',
            name='ramo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.ramo'),
        ),
    ]
