# Generated by Django 4.2.9 on 2024-06-11 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimentacoescliente',
            old_name='categotiria',
            new_name='categoria',
        ),
    ]
