# Generated by Django 5.0.6 on 2025-06-24 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0002_initial'),
        ('financeiro', '0001_initial'),
        ('hpinicial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bancoscliente',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hpinicial.tenant'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cadastro_de_cliente'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hpinicial.tenant'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='categoriamae',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.categoriamae'),
        ),
        migrations.AddField(
            model_name='centrodecusto',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cadastro_de_cliente'),
        ),
        migrations.AddField(
            model_name='centrodecusto',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hpinicial.tenant'),
        ),
        migrations.AddField(
            model_name='movimentacoescliente',
            name='banco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.bancoscliente'),
        ),
        migrations.AddField(
            model_name='movimentacoescliente',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.categoria'),
        ),
        migrations.AddField(
            model_name='movimentacoescliente',
            name='centrodecusto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.centrodecusto'),
        ),
        migrations.AddField(
            model_name='movimentacoescliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cadastro_de_cliente'),
        ),
        migrations.AddField(
            model_name='movimentacoescliente',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hpinicial.tenant'),
        ),
        migrations.AddField(
            model_name='regra',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.categoria'),
        ),
        migrations.AddField(
            model_name='regra',
            name='centrodecusto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.centrodecusto'),
        ),
        migrations.AddField(
            model_name='regra',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cadastro_de_cliente'),
        ),
        migrations.AddField(
            model_name='regra',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hpinicial.tenant'),
        ),
        migrations.AddField(
            model_name='saldo',
            name='banco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.bancoscliente'),
        ),
        migrations.AddField(
            model_name='saldo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cadastro_de_cliente'),
        ),
        migrations.AddField(
            model_name='saldo',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hpinicial.tenant'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.categoria'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cadastro_de_cliente'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hpinicial.tenant'),
        ),
        migrations.AddField(
            model_name='regra',
            name='subcategoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.subcategoria'),
        ),
        migrations.AddField(
            model_name='movimentacoescliente',
            name='subcategoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.subcategoria'),
        ),
        migrations.AddField(
            model_name='transicaocliente',
            name='banco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.bancoscliente'),
        ),
        migrations.AddField(
            model_name='transicaocliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cadastro_de_cliente'),
        ),
        migrations.AddField(
            model_name='transicaocliente',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hpinicial.tenant'),
        ),
        migrations.AddConstraint(
            model_name='saldo',
            constraint=models.UniqueConstraint(fields=('banco', 'cliente', 'data'), name='unique_banco_cliente_data'),
        ),
    ]
