# Generated by Django 4.2.9 on 2024-06-20 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('financeiro', '0002_rename_categotiria_movimentacoescliente_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('saldoinicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldofinal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('banco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.bancoscliente')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cadastro_de_cliente')),
            ],
        ),
    ]
