# Generated by Django 4.2.9 on 2024-06-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldo',
            name='saldofinal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
