# Generated by Django 5.0.6 on 2024-06-25 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_alter_saldo_saldofinal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldo',
            name='saldoinicial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
