# Generated by Django 5.0.6 on 2024-07-24 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('financeiro', '0006_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank='Sem Descrição', max_length=100)),
                ('ativo', models.BooleanField(blank=True, null=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.categoria')),
                ('centrodecusto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.centrodecusto')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cadastro_de_cliente')),
                ('subcategoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.subcategoria')),
            ],
        ),
    ]
