# Generated by Django 5.0.6 on 2024-07-30 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('financeiro', '0007_regra'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransicaoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.CharField(blank='Sem Descrição', max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('banco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.bancoscliente')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cadastro_de_cliente')),
            ],
        ),
    ]
