# Generated by Django 5.0.6 on 2024-08-06 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0008_transicaocliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldo',
            name='banco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.bancoscliente'),
        ),
    ]
